### ISSUE TITLE
Dependency search JspAnalyzer has a NullPointerException if the uri attribute does not exist in the taglib definition .

### ISSUE THREAD

**Issue by azkaoru** [TUBAME/migration-tool#115]
Dependency search JspAnalyzer has a NullPointerException if the uri attribute does not exist in the taglib definition (see example.jsp)

tubame.wsearch.log

```
tubame.wsearch.biz.ex.WSearchBizException: java.lang.NullPointerException
	at tubame.wsearch.biz.analyzer.jsp.JspAnalyzer.analyze(JspAnalyzer.java:314) ~[tubame-wsearch-biz-1.1.1-SNAPSHOT.jar:na]
	at tubame.wsearch.biz.process.WSearchAnalyzeAndCompareProcessor$AnalyzeAndCompareTask.call(WSearchAnalyzeAndCompareProcessor.java:226) ~[tubame-wsearch-biz-1.1.1-SNAPSHOT.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_74]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
Caused by: java.lang.NullPointerException: null
	at tubame.wsearch.biz.analyzer.jsp.JspAnalyzer.parseTaglibDirective(JspAnalyzer.java:979) ~[tubame-wsearch-biz-1.1.1-SNAPSHOT.jar:na]
	at tubame.wsearch.biz.analyzer.jsp.JspAnalyzer.parseDirective(JspAnalyzer.java:446) ~[tubame-wsearch-biz-1.1.1-SNAPSHOT.jar:na]
	at tubame.wsearch.biz.analyzer.jsp.JspAnalyzer.parseElements(JspAnalyzer.java:389) ~[tubame-wsearch-biz-1.1.1-SNAPSHOT.jar:na]
	at tubame.wsearch.biz.analyzer.jsp.JspAnalyzer.analyze(JspAnalyzer.java:311) ~[tubame-wsearch-biz-1.1.1-SNAPSHOT.jar:na]
	... 5 common frames omitted

```

example.jsp

```
<%@ taglib tagdir="/WEB-INF/tags" prefix="tags"%>
```

**Comment by azkaoru** [comment]
close
