### ISSUE TITLE
External python tool probably not found: ext_search_tag_has_attribute ?

### ISSUE THREAD

**Issue by akram** [TUBAME/migration-tool#4]
The previous issue was probably due to the following issue:
2013-10-29 16:49:37,755 [ModalContext] ERROR t.p.p.w.AbstractSearchToolWithProgress - Failed files:
  File "/Users/Akram/tools/eclipse/plugins/tubame.portability_1.0.0.201310021343/resources/tubame-search-modules/src/jbmst.py", line 195, in <module>
Cause:
KeyError: 'extend.ext_search_tag_has_attribute'
2013-10-29 16:49:37,783 [main] ERROR t.p.plugin.wizard.JbmSearchWizard - Search processing ended abnormally.
java.lang.reflect.InvocationTargetException: Failed files:
  File "/Users/Akram/tools/eclipse/plugins/tubame.portability_1.0.0.201310021343/resources/tubame-search-modules/src/jbmst.py", line 195, in <module>
Cause:
KeyError: 'extend.ext_search_tag_has_attribute'
	at tubame.portability.plugin.wizard.AbstractSearchToolWithProgress.run(AbstractSearchToolWithProgress.java:202) ~[tubame.portability_1.0.0.201310021343/:na]
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121) ~[org.eclipse.jface_3.9.0.v20130521-1714.jar:na]
Caused by: tubame.portability.exception.JbmException: null

See gist:
https://gist.github.com/akram/7217270

**Comment by TUBAME** [comment]
Perhaps, in the latest version, this problem does not occur.
thank you for repoting
